### ISSUE TITLE
[Feature Request] Import YouTube Playlists

### ISSUE THREAD

**Issue by cassidoo** [dubtrack/www-dubtrack-fm#33] opened 2015-09-29 15:11 UTC

**Comment by chrisrohn** [comment] 2015-09-29 15:30
duplicate of #3

**Comment by joedubtrack** [comment] 2015-09-30 18:45
@cassidoo Hey Cassidy, thank you so much for contributing! If you like, we have a SLACK for our developers as well as other volunteers working on the project. We would love to have you around :)

**Comment by cassidoo** [comment] 2015-09-30 20:35
@joedubtrack I'd love to!  How can I join?

**Comment by joedubtrack** [comment] 2015-09-30 21:33
@cassidoo send me an email joe@dubtrack.fm and ill send you an invite

**Closed** 2015-11-10 05:02 UTC
