### ISSUE TITLE
[Feature Request] Commands in chat

### ISSUE THREAD

**Issue by cassidoo** [dubtrack/www-dubtrack-fm#35] opened 2015-09-29 15:13 UTC
Commands like `/me` `/whatever` `/giphy` would be great for the chat rooms.

**Comment by scytheria1001** [comment] 2015-09-29 15:27
duplicate of #22

**Comment by PhilipShilling** [comment] 2015-09-29 15:29
This is being worked on by myself and is a duplicate as stated by @scytheria1001

**Closed by PhilipShilling** 2015-09-29 15:29 UTC
