### ISSUE TITLE
Playback Glitches / Skips Back

### ISSUE THREAD

**Issue by andrewtibbetts** [dubtrack/www-dubtrack-fm#2] opened 2015-09-23 14:47 UTC
Songs randomly skip back a few seconds. Not consistent as far as I can tell. Sometimes it jumps back 5 or 6 seconds, sometimes 1 or 2. Usually 2-10 times a song. Some people don't experience it at all. I experience it constantly. Maybe a syncing issue that can be pushed to the space in between songs (shot in the dark)?

**Comment by nambok** [comment] 2015-09-23 15:46
@andrewtibbetts yeah this bug was reported already and we are working on a fix for it, will let you know when is fixed

**Comment by METALBUTTCHEEKS** [comment] 2015-09-23 16:44
Adding to this, I've seen this happen in Chrome when switching tabs constantly.

**Comment by Jaymus3** [comment] 2015-09-23 19:07
I also noticed this issue and was thinking about how it might be happening.  The way that plug dj seems to "sync" music playback is by trying to start the songs at the same time.  This is noticeable especially if you have internet that can be a bit touchy at times like mine.  Sometimes videos will take a little while to buffer, leaving me slightly behind.  This isn't a big deal unless I planned on singing along with someone, but it cuts off the end of the song for me sometimes because it's only supposed to play for that period of time.  It seemed like the sync issue was happening when my internet would have random hiccups, which leads me to believe that you're syncing the songs constantly with some sort of server timer?  If I knew more about web development, I'd fully understand how you guys handle it but unfortunately I don't.  If you are using a timer like that, maybe just use the plug system of starting at the same time and don't force people to sync to the exact time unless they get like 10-15 seconds out of sync.  I'm fine with losing a few seconds off the end of the song if it means it won't re-play parts of the song over again

**Comment by nambok** [comment] 2015-09-23 19:13
@Jaymus3 you are 100% right thats how we do it, here is the piece of code that takes care of syncing the song https://github.com/dubtrack/www-dubtrack-fm/blob/staging/public/assets/js/dubtrack/src/views/room/player.view.js#L533. We can increase it to 15 seconds

**Comment by Jaymus3** [comment] 2015-09-23 19:33
If that doesn't fix the issue, maybe the problem isn't people falling behind, but instead getting ahead somehow. (I say this because I might be remembering it wrong, but I remember hearing the same part twice, which would mean it had to set me back).  Why do you have totalTime and currentTime comparing both ways?  What circumstance would ever cause the user to have gotten ahead of the server's timer?  The server never has to buffer the video or anything to start the timer, so as far as I can tell, that timer should always be ahead if anything, but never behind the user unless the user was getting started too early.

**Comment by nambok** [comment] 2015-09-23 19:37
@Jaymus3 we never had it getting ahead but just in case people find a way to skip ahead.

`totalTime` is the current server time and `currentTime` is the player time. I think i have fix for this Ill submit a PR later today

**Comment by andrewtibbetts** [comment] 2015-09-24 16:28
Nice! Whatever the solution, please don't have any mid-song adjustments. Start the song late or end it early. Skips in the middle of the song make it unlistenable.

**Comment by missmiskelly** [comment] 2015-09-24 16:39
@nambok - I agree with @andrewtibbetts. Mid song adjustments is totally distracting and starting to drive me crazy! My account skips back constantly, then cuts off the end of each song. I'd rather wait for the next song in the queue then listen to the same line of the song 5 times before it cutting off. Is there any way to disable that syncing feature?

**Comment by nambok** [comment] 2015-09-25 15:08
@missmiskelly working on a fix for this, will have it ready over the weekend thanks for your patience and apologies for the issue

**Closed** 2015-09-26 19:47 UTC
Labels: bug

**Comment by ghost** [comment] 2016-03-19 06:55
i'm still getting this

constant buffering, even when YT is loading 144p video source. works fine on the original youtube URL, it's just on this website it lags to the point it's unusable. enver had this issue on cytube or plug.dj or any other website that does this syncing youtube chatroom stuff.

**Comment by RobGoldy** [comment] 2016-03-19 17:55
Does not sound like a problem with the website. Sounds like you need to fix something with your cpu.
