### ISSUE TITLE
Songs not playing when added to the que

### ISSUE THREAD

**Issue by apdjz** [dubtrack/www-dubtrack-fm#292] opened 2016-07-01 15:15 UTC
It says no que, but there is a que
https://i.gyazo.com/c148fe40a61dfe6f310a13c2c2e4f482.png

https://i.gyazo.com/678a9b1d1d7e747746e0737213f34271.png

Yes I tried refreshing and creating a new room.

**Comment by starnixce** [comment] 2016-07-01 15:33
This is a site-wide issue atm. We switched real time services and are experiencing some issues since switching. They are working on it with us to get things restored asap.

**Comment by Larry1123** [comment] 2016-07-01 16:56
Going to leave this open for a little bit. This should be fixed now. We will be watching to make sure this does not happen again.

**Comment by Larry1123** [comment] 2016-07-03 00:42
I think I have a working fix for this (Has to do with the lag on skipping and song changes). I will close this after it is live and we have confirmed that it works.

**Comment by Larry1123** [comment] 2016-07-03 01:45
This should be fixed now. If it happens again make a new issue. Thanks.

**Closed as completed by Larry1123** 2016-07-03 01:45 UTC
Labels: bug
