### ISSUE TITLE
[Feature Request] Allow to change song label

### ISSUE THREAD

**Issue by jsmoro** [dubtrack/www-dubtrack-fm#262] opened 2016-03-04 13:21 UTC
Sometimes the song grabbed from YT or SC is not named correcty (or name is incomplete).
Allow to change the label or provide a new field would be a great feature.
To set the Artist Name for example.

**Comment by coryshaw1** [comment] 2016-03-04 14:19
Duplicate of #7 and #123

**Closed as completed** 2016-05-15 01:40 UTC
Labels: duplicate
